---
- hosts: localhost
  connection: local
  become: true
  
  tasks:
    - name: install pip3 and common pkgs
      apt:
        state: latest
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools 
    - name: pip install pandas
      pip:
        name: pandas
    - name: pip install requests
      pip:
        name: requests
    - name: pip install numpy
      pip:
        name: numpy